name: Run benchmarks
on: pull_request

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: julia-actions/setup-julia@v1
      with:
        version: 1.5
    - uses: julia-actions/julia-buildpkg@latest
    - name: Instantiate
      run: julia --project=benchmark -e 'import Pkg; Pkg.instantiate()'
    - name: Run benchmarks
      run: julia --project=benchmark benchmark/runbenchmarks.jl
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
