name: CI
on: [push, pull_request]

jobs:
  # This workflow contains a single job called "build"
  test:
    name: Tests - julia ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ['1.0', '1', 'nightly']
    steps:
    - uses: actions/checkout@v2
    - uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.version }}
    - uses: julia-actions/julia-buildpkg@latest
    - uses: julia-actions/julia-runtest@latest
    - uses: julia-actions/julia-processcoverage@v1
    - uses: codecov/codecove-action@v1
      with:
        file: lcov.info

  benchmark:
    name: Benchmarks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: julia-actions/setup-julia@v1
      with:
        version: 1.5
    - uses: julia-actions/julia-buildpkg@latest
    - run: |
        julia --project=benchmark -e 'import Pkg; Pkg.instantiate()'
    - run: |
        julia --project=benchmark benchmark/runbenchmarks.jl
        
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
    - run: echo "TODO"
